### PR TITLE
Add a make script to generate all files, update all files according to new make script

### PR DESCRIPTION
**Pull request by desaintmartin**
As I wanted to do a simple patch to uwsgi-nginx-docker, I gave up and wrote a make script instead, in order not to have to write 12 times the same change and to not diverge between versions.

This is a first draft not to be merged right now but I would like to get feeback already.

### CODE REVIEW

**Comment by tiangolo** [comment]
Thanks! The problem is that there are slight differences, for example between Alpine and standard (Debian) versions.

The location of configurations, and shell scripts varies a little too.

**Comment by desaintmartin** [comment]
Do you think it is a good idea and that we should carry on?
I have not much time those days but it's an idea I would like to get implemented as it gets harder and harder to do changes in this repository as we get more and more OS/python versions.

**Comment by tiangolo** [comment]
I think we can close it for now.

We would have to implement quite some logic to handle de nuances/differences between versions, we would have another dependency, and another set of files to maintain.

The good thing is that, although the code underneath has slight differences, the tests are more homogeneous, so everything is being tested to work properly.

**Comment by tiangolo** [comment]
I'm going to close this now, but thanks for your help! :cake: :rocket:

**Pull request closed without merging**
