### PR TITLE
✨ Add Python 3.9

### LINKED ISSUE #100: Python 3.9 images
Hi there,

Would it be possible to get Python 3.9 (alpine) images?

### PR DESCRIPTION
**Pull request by sjadema**
Related to #100
Related to #99 

I tried to add 3.9 Alpine as well but Alpine's [`uwsgi-python3`](https://pkgs.alpinelinux.org/package/edge/main/x86/uwsgi-python3) package doesn't support it yet.

### CODE REVIEW

**Comment by mahenzon** [comment]
Then will need to upgrade dependant projects such as [uwsgi-nginx-flask-docker](https://github.com/tiangolo/uwsgi-nginx-flask-docker)
I'll create a PR

**Comment by looser990** [comment]
Hey guys, is there any ETA on this? Do you have roadmap where I can follow this kind of stuff?

**Comment by pupattan** [comment]
Hey, is there any ETA on this?

**Comment by tiangolo** [comment]
Awesome, thanks for your contribution! :rocket: :coffee:

**Pull request merged**
