### PR TITLE
Implement python3.8 version

### LINKED ISSUE #73: Python 3.8
Would love to see a python 3.8 version of this project :)

These are super nice images, they pair awesomely with traefik 👍

### PR DESCRIPTION
**Pull request by Dutchy-**
I did the following:

- Copied `python3.7` directory to `python3.8`.
- Changed mentions of `stretch` to `buster` where relevant.
- Changed `nginx` and `nginx-module-njs` versions to the latest available versions.
- Added a travis config (but I don't know much about travis).

This should fix #73 . When this is done I also plan to fix the flask version.

I tested the new build as follows:

```bash
$ docker build -t uwsgi-nginx-test python3.8
...
$ pytest tests      
================================================== test session starts ==================================================
platform darwin -- Python 3.8.1, pytest-5.3.4, py-1.8.1, pluggy-0.13.1
rootdir: /Users/dutchy/Documents/Northwave/uwsgi-nginx-docker
plugins: celery-4.4.0, mock-2.0.0, flask-sqlalchemy-1.0.2, flask-0.15.0
collected 5 items                                                                                                       

tests/test_01_main/test_defaults.py .                                                                             [ 20%]
tests/test_01_main/test_env_vars_1.py .                                                                           [ 40%]
tests/test_02_app/test_app_and_env_vars.py .                                                                      [ 60%]
tests/test_02_app/test_custom_nginx_app.py .                                                                      [ 80%]
tests/test_02_app/test_simple_app.py .                                                                            [100%]

=================================================== 5 passed in 1.43s ===================================================
```

Let me know if I missed anything.

### CODE REVIEW

**Comment by Dutchy-** [comment]
Since python:3.8 is based on Debian Buster, this should also fix #64

**Comment by inhumantsar** [comment]
Looking forward to having this merged in

**Comment by tiangolo** [comment]
Thanks for your contribution @Dutchy- :cake: !

And thanks everyone for the discussion here :coffee: 

I recently realized that all the setup was quite complex, and I refactored it all and simplified it.

Now I just added Python 3.8 support in a new PR on top of that with the new setup.

But thanks for your effort! :nerd_face: :rocket: :tada:

**Comment by Dutchy-** [comment]
The end result is what matters, thanks for the 3.8 support!

**Pull request closed without merging**
