### PR TITLE
uwsgi: force an application to be loaded or die.

### PR DESCRIPTION
**Pull request by desaintmartin**
Avoid 'silent' error where no app is found yet uwsgi continues to run.

### CODE REVIEW

**Comment by desaintmartin** [comment]
Gentle up?

**Comment by desaintmartin** [comment]
I've just realized this is ALREADY done since a few months. It may be cleaner to use this way (less surprise), if you agree I can update the PR, otherwise I'll just close!

**Comment by tiangolo** [comment]
Sorry for the delay :sweat_smile: .
Can you elaborate on how it would be less of a surprise than what is currently done (in the Supervisor command)?

**Comment by desaintmartin** [comment]
I think I've missed your comment.
Well, just is just a matter of centralizing the configuration. This is not that important but it makes it more obvious (to know what configuration uwsgi uses, just look at the config file) and more configurable (easier to override).

**Comment by tiangolo** [comment]
Thanks @desaintmartin !

I included this and added all the extra configs to the .ini file as you suggested.

Including one extra to support the new testing parts.

**Pull request merged**
